---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Downloading {{ talos_url }} to {{ talos_installed_exe }}
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: '{{ talos_url }}'
    dest: '{{ talos_installed_exe }}'
    checksum: '{{ talos_checksum }}'
    mode: '755'
- name: Linking {{ talos_link }} to {{ talos_installed_exe }}...
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ talos_installed_exe }}'
    dest: '{{ talos_link }}'
    state: link
